### ISSUE TITLE
1. AWeber Form 

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#1]
>1. AWeber Form - Each archetype (result) has it’s own separate form. In total, we have 12 different forms with follow-up sequences catered to the specific results. I noticed in the index.js file that you’ve only specified 1 form (Ruler). The flow that we need is for the form to correspond with the result. So if the user gets the Member, on the reuslts page of the quiz will be the form for the Member. And if a user gets the Innocent, the results page of the quiz will be the form for the Innocent. How can we have this implemented?

**Comment by freethlua** [comment]
Aweber data for different archetypes now stored in [`/data/archetypes.js`](../blob/master/data/archetypes.js).

**Comment by zhixinlin** [comment]
Hi Freeth,

It seems to be working fine now. Will have this checked more thoroughly to ensure all forms are functioning correctly. Thanks!
