### ISSUE TITLE
12. compatibility slider - logo bottom, image top

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#11]
>12. This is an update to the image slider. For the love compatibility image, would it be possible to make it follow the attached image? (opacity 0.7, logo shift to bottom for entire duration instead of on top, full width 100%). Please specify opacity 0.7 for all other images (e.g. archetype icons, spiritual, globe) as well

[![image](https://user-images.githubusercontent.com/8020662/27652959-2f47cdc0-5c5b-11e7-9c88-f702556bc57a.png)](https://sa1-api.asm.skype.com/v1/objects/0-sa-d4-38d4ed9958f50ebe6b108102d68a8c20/views/imgpsh_fullsize)

**Comment by freethlua** [comment]
Fixed. Test with: http://individualogist.com/whats-your-archetype-v2/?dev&report=free&archetype=jester&seekTo=500

**Comment by wilsonljx** [comment]
The love compatibility is still overlaying at my side.

<img width="927" alt="screen shot 2017-06-30 at 10 42 33 am" src="https://user-images.githubusercontent.com/29788050/27718815-f8c84f6e-5d80-11e7-8c92-24b8846b2ccd.png">

**Comment by freethlua** [comment]
Definitely fixed now. Test with: http://individualogist.com/whats-your-archetype-v2/?dev&report=free&archetype=jester&seekTo=500
