### ISSUE TITLE
13. Browser cache directing to quiz result page instead of text slider

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#12]
Hi Freeth,

Just noticed that the caching function you created now directs users who visit whats-your-archetype-v2 to the quiz result page (the page with the aweber optin form) instead of directing them straight to the text slider. Can you please have this changed back to the text slider instead? This is a non-priority issue. Thanks!

**Comment by freethlua** [comment]
fixed
