### ISSUE TITLE
Continuous integration on individualogist.com server 

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#13]
Continuously updating code on individualogist.com server is currently bit of a chore. 

Currently, in order to update the code on individualogist.com server, I do the following:

1. SSH into the server
   * Since i have [dynamic IP I have to add it to the firewall](http://www.inmotionhosting.com/support/website/ssh/add-ip-to-firewall) through cpanel whenever it changes
     
      Allowing **all** IPs to SSH would be helpful, and the risk it poses can be mitigated by only allowing SSH through private keys (I've set up one for myself on the server already) instead of password. 
2. Do a git pull

To allow automatically updating the code on server whenever I push code to this (or bitbucket) repository  from my machine, either of the following is needed on the server:

* nodejs ([git-auto-pull](https://github.com/Keenpoint/git-auto-pull)).
* [setting up a git server](https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server)
  
Both require installation (sudo) which isn't allowed on current server, [it requires a dedicated host](https://www.google.com/search?q=inmotionhosting+install+node+js).

 **This is currently already possible on [github.io demo](http://freethlua.github.io/individualogist-whats-your-archetype/) so please refer to that for an always-latest demo (in case I wasn't able to update indivialogist server).**

PS: Aweber is disabeled on github demo, it only works when redirect URL is individualogist.com

**Comment by zhixinlin** [comment]
Hi Freeth,

No worries - will refer to the github.io demo instead from here on out. Do whatever you need to do to make your job easier. Thanks!
