### ISSUE TITLE
Code are showing on the Sliders

### ISSUE THREAD

**Issue by wilsonljx** [freethlua/individualogist-whats-your-archetype#15]
Hi Freeth,

Please check all the sliders and the coding are appearing on all the sliders(I have only checked member and jester)

Please check the image.
<img width="933" alt="screen shot 2017-06-30 at 9 39 13 am" src="https://user-images.githubusercontent.com/29788050/27717592-d6d94d34-5d78-11e7-80a2-fccf89c48d48.png">

**Comment by freethlua** [comment]
fixed
