### ISSUE TITLE
 compatibility slider - logo bottom, image top

### ISSUE THREAD

**Issue by wilsonljx** [freethlua/individualogist-whats-your-archetype#16]
The love compatibility is still overlaying at my side.

<img width="927" alt="screen shot 2017-06-30 at 10 42 33 am" src="https://user-images.githubusercontent.com/29788050/27718815-f8c84f6e-5d80-11e7-8c92-24b8846b2ccd.png">

**Comment by freethlua** [comment]
Fixed. Test with: http://individualogist.com/whats-your-archetype-v2/?dev&report=free&archetype=jester&seekTo=500

**Comment by freethlua** [comment]
Added some responsiveness to compatibility image as well:

[![](https://thumbs.gfycat.com/ExaltedConstantArabianhorse-size_restricted.gif)](https://gfycat.com/ExaltedConstantArabianhorse)

**Comment by zhixinlin** [comment]
Hi Freeth,

After the love compatibility image fades out, the text sticks to the top instead of being vertically centred. Could you fix this? Thanks!

**Comment by freethlua** [comment]
Fixed. Test with: http://individualogist.com/whats-your-archetype-v2/?dev&report=free&archetype=creator&seekToIndex=143  You can hit <kbd>Ctrl</kbd><kbd>Up</kbd> to speed it up
