### ISSUE TITLE
Changes to the time stamp scripts

### ISSUE THREAD

**Issue by wilsonljx** [freethlua/individualogist-whats-your-archetype#17]
We have did some changes to all the time stamp scripts

Please use this for the latest revision.

https://drive.google.com/drive/folders/0B6hspEf5nVh0UkJaT1Q5ZVlMeXM?usp=sharing

Thanks!

**Comment by freethlua** [comment]
Updated

**Comment by zhixinlin** [comment]
Hi Freeth,

I'm a little bit puzzled - we were pretty careful with our timestamps to try and make it perfect as possible, but in the text slider, the speed doesn't seem to match the VO. I'm guessing that there's some form of rounding in the txt to js, so accuracy is affected (e.g. timing 01s56ms is rounded up to 02s00ms.) Is there a way we can make the text and VO more synchronised? We're fine with retranscribing everything, perhaps you could point us in the right direction. Thanks!

**Comment by freethlua** [comment]
I had it set to advance -1 second earlier as a way to fix some timing issues. Not rounding off or anything, they were just 1 second in advance. 

The new timestamps are perfect and work well without any adjustments from my side. 

So fixed now.
