### ISSUE TITLE
First follow up goes to promotion tab in gmail

### ISSUE THREAD

**Issue by wilsonljx** [freethlua/individualogist-whats-your-archetype#18]
Do you have any idea how we can fix this? It seems like when I opted in, the first follow up goes to promotion tab instead of the inbox in gmail.

Not too sure if it's because of the customised web app that gmail decides to filter it into the promotion tab.

**Comment by freethlua** [comment]
Not much experience with campaigning but I'll investigate. I'm assuming you haven't changed anything else, like on Aweber? Let me know aweber details (email: <redacted/>). 

A [cursory search](https://www.google.co,/search?q=follow+up+goes+to+promotion+tab+in+gmail) shows following guidelines, make sure you're following those:

https://www.smartpassiveincome.com/how-to-land-your-emails-in-the-gmail-primary-tab-every-time/
https://www.digitaldoughnut.com/articles/2016/may/anxious-how-to-avoid-gmail-promotions-tab-worry-n

1. Have no more than one link in your email.
3. Include no pictures.
4. Mention the reader’s name using Merge Tag Tricks with MailChimp or Aweber.
5. Turn off the RSS Campaign. If you want a higher open count, you must type these emails out by hand.
6. Write to the reader like they are your friend.
7. Don’t go spammy like this: Hey!!! WANT TO MAKE MONEY FAST??!?!?!
8. Write in Traditional Letter Form.

**Comment by freethlua** [comment]
I dug out an old email from when I first signed up on the original site before making any modification and it was too categorized as "Promotions" by gmail. Maybe this problem already existed earlier as well.

**Comment by wilsonljx** [comment]
Sure, just sent you the details. Probably u can let us know how to ensure all of the emails are being sent to the inbox tab.

Thanks

**Comment by zhixinlin** [comment]
Hi Freeth,

No worries about this, we know this is probably beyond your control. Thanks :)
