### ISSUE TITLE
Testimonial not optimized for my monitor

### ISSUE THREAD

**Issue by wilsonljx** [freethlua/individualogist-whats-your-archetype#19]
Hi,

It seems like the testimonial below the slider has a lot of spacing between the text and the video. Please optimize it to all the devices.

![6](https://user-images.githubusercontent.com/29788050/27760108-0172e5e2-5e72-11e7-86b9-b71739965f56.png)

**Comment by freethlua** [comment]
Fixed: 

[![](https://thumbs.gfycat.com/PhysicalNiceIndianringneckparakeet-size_restricted.gif)](https://gfycat.com/PhysicalNiceIndianringneckparakeet)
