### ISSUE TITLE
order page /deluxe links

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#2]
>2. On the text slider page, the order buttons have all been configured to point to the ruler. But once again, we have 12 different archetypes (results). And each result has it’s own separate report, which requires a separate link to the payment page. Initially, we had 12 different pages for each archetype, and each page also has an exit-pop to a discount page (i.e. if they try to close the window, a pop-up will appear). This is incredibly important as the exit-pop accounts for about 30-40% of our sales for the front-end report. What’s the best way to have this configured? Should we make it dynamic, or would it be better to duplicate the slider into 12 different pages and set each of them up separately? Let me know your thoughts on this.

**Comment by freethlua** [comment]
I found that links are like this:

```
http://dar-[cre|jes|rul|...].individua1.pay.clickbank.net/?cbskin=...
```
I.e. the sub-domain is different for each archetype: `dar-cre.individua1.pay`, `dar-jes.individua1.pay`, ... and have the first 3 characters of each archetype. I've used this logic to update the links. 

Hope this fixes it. Let me know if there's other variation in links. This info may also be stored with archetype data as solved in #1

**Comment by zhixinlin** [comment]
Hi Freeth,

Here are the links for each archetype for your reference. The format is more or less the same, but each URL also has a different flow id. The flow id triggers a configuration in Clickbank to begin a process of upsells, it's a feature that's very important for us. I'm not sure if you took that into account, but just in case you didn't, here are all the links:

Caregiver: http://dar-car.individua1.pay.clickbank.net/?cbskin=16829&cbfid=28769
Creator: http://dar-cre.individua1.pay.clickbank.net/?cbskin=16829&cbfid=27121
Explorer: http://dar-exp.individua1.pay.clickbank.net/?cbskin=16829&cbfid=28787
Hero: http://dar-her.individua1.pay.clickbank.net/?cbskin=16829&cbfid=28788
Innocent: http://dar-inn.individua1.pay.clickbank.net/?cbskin=16829&cbfid=28789
Jester: http://dar-jes.individua1.pay.clickbank.net/?cbskin=16829&cbfid=28790
Lover: http://dar-lov.individua1.pay.clickbank.net/?cbskin=16829&cbfid=28791
Member: http://dar-mem.individua1.pay.clickbank.net/?cbskin=16829&cbfid=28793
Magician: http://dar-mag.individua1.pay.clickbank.net/?cbskin=16829&cbfid=28792
Outlaw: http://dar-out.individua1.pay.clickbank.net/?cbskin=16829&cbfid=28794
Ruler: http://dar-rul.individua1.pay.clickbank.net/?cbskin=16829&cbfid=28795
Sage: http://dar-sag.individua1.pay.clickbank.net/?cbskin=16829&cbfid=28797

**Comment by freethlua** [comment]
Fixed.
