### ISSUE TITLE
Action 1 Button Not Clickable On Larger Screens

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#20]
Hi Freeth

We've encountered an issue with action 1 (the first CTA that sits between the text slider). On larger screens, the button cannot be clicked. It works fine on 13-15" monitors but 25" or so, it's not clickable

Could you look into this? Thanks!

**Comment by wilsonljx** [comment]
Hi Freeth,

Aaron here. Please add CSS z-index: 1 to action1 button. This should resolve the issue. Thanks!

**Comment by freethlua** [comment]
done
