### ISSUE TITLE
Styling edits

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#21]
Hi Freeth,

The following are the styles for your reference (attached screenshot)
![screencapture-individualogist-whats-your-archetype-v2-1499142274507](https://user-images.githubusercontent.com/19595715/27815045-cb68f51a-60b3-11e7-8e71-869a4df9239c.png)
:

Action 1 purple bg 
{
box-shadow: 10px 15px 20px rgba(0, 0, 0, 0.75);
}

Action1  button
{
cursor: pointer;
   text-shadow: 0 0 3px #fff;
    font-size: 1.3em;
    font-weight: 700;
    color: #222;
    background: linear-gradient(to right, #e4c22c, #f8b144);
    border-radius: 50px;
    box-shadow: 10px 10px 10px rgba(51, 51, 51, 0.75);
    padding: 0.5em;
}

testimonial container {
    background: #009cff;
    font-size: 1.3em;
}

testimonial youtube video (remove right margin to make section full width)
{
margin-right: 0;
}

action 2 (make form longer and shift image left so as to not cover text in the form)
{
max-width: 1000px
}

footer (change copyright year to auto and add ahref links)
<script type="text/javascript">
  document.write(new Date().getFullYear());
</script>

<a href=”http://individualogist.com/terms-and-conditions/”>Terms and Conditions</a>
<a href=”http://individualogist.com/privacy-policy/”>Privacy Policy</a>
<a href=”http://individualogist.com/contact/”>Contact</a>
ADD THIS • <a href=”http://individualogist.com/jv-register/”>Affiliates</a>
(remember circular separator after contact)

Play button (replace with attached play.png)
![play](https://user-images.githubusercontent.com/19595715/27815037-b2bb6c5a-60b3-11e7-88ea-30f001695206.png)

**Comment by zhixinlin** [comment]
Hi Freeth,

Thank you for the prompt response and the swift action!

I see that you've made a lot of the changes already. We're pretty much ready to bring this project to a close, but there's just 2 more minor styling issues that we have to fix that I came across:
![img_9308](https://user-images.githubusercontent.com/19595715/27847740-302c346c-6172-11e7-8e13-7383527186cf.PNG)

1. Facebook comments not responsive. Please refer to attached screenshot showing that the FB comments section isn't staying in it's container. Device is iPhone 6. I'm not sure why though.

2. Footer links. Please add in the following CSS for a hrefs footer:
    text-decoration: none;
    text-transform: capitalize;
    color: #a32ff5;
And also the link for Affiliates should be /jv-register instead of /affiliates

That's pretty much it for now. Everything else is great. Thanks so much!

**Comment by freethlua** [comment]
All done except I couldn't reproduce the facebook comments issue, but I've made some changes that might fix it, please test again and let me know.

**Comment by zhixinlin** [comment]
Hi Freeth,

Please refer to the screenshot below. The spacing on the left of the quiz still exists, and there's also code showing below it. Space is seen on all mobile devices. Code is only visible on iPhone 6 Plus. Browser used is Safari. Let me know if you need any more info on this. Thanks!

![whatsapp image 2017-07-05 at 2 18 05 pm](https://user-images.githubusercontent.com/19595715/27851381-dbcf8a3e-618c-11e7-84f1-e4de69bf5912.jpeg)

**Comment by zhixinlin** [comment]
Looks like the issue with the FB comments area is a Safari-specific issue.

There's also display issues with the entire quiz on Firefox. Could you look into this as well? Thanks so much

**Comment by freethlua** [comment]
Made some changes, please checkout and update me once again. 

Could you please also share the screenshot for Firefox? (it was working ok on my side)

**Comment by zhixinlin** [comment]
Hi Freeth,

Oops Firefox works fine, had to update my browser was all. We're testing different browsers/devices at the moment. Will keep you updated if we encounter any other issues

But still encountering display issues with iPhone. The FB comments section has disappeared and been replaced with a really long empty space.

**Comment by zhixinlin** [comment]
![whatsapp image 2017-07-05 at 3 22 45 pm](https://user-images.githubusercontent.com/19595715/27853591-e6ae03d2-6195-11e7-937c-dbc18c748e1b.jpeg)

Above screenshot is display on Chorme in Kindle (tablet equivalent I suppose). It goes to a blank page. Same issue on Internet Explorer on desktop. Inspect element shows that CSS styles are not being detected, which leads to nothing being displayed. I'm not sure :/

![whatsapp image 2017-07-05 at 3 27 18 pm](https://user-images.githubusercontent.com/19595715/27853732-80e50950-6196-11e7-9f6d-4f4865cf3360.jpeg)

**Comment by freethlua** [comment]
Moved to separate issues: fb-comments: #26, IE: #27
