### ISSUE TITLE
Exit pop

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#22]
Hi Freeth,

We need to add one last final thing, the exit pop for each archetype reading. I'm not sure if you're able to do this dynamically, but if you are, here are the details.

You can see the exit pop in action on this page when you attempt to close it:
http://individualogist.com/deluxe-archetype-report-ruler-reading-3/

Exit pops account for approximately 30% of our conversions, so it's imperative that we add this function or something equivalent.

This is the script that we're currently working with, and what we'll need you to add (it doesn't have to be this script, but if you have something that works better, we're definitely up for it):

<script language="javascript">(function() { setTimeout(function() { var __redirect_to = 'http://individualogist.com/deluxe-archetype-report-ruler-reading-3/'; var _tags = ['button', 'input', 'a'], _els, _i, _i2; for(_i in _tags) { _els = document.getElementsByTagName(_tags[_i]); for(_i2 in _els) { if((_tags[_i] == 'input' && _els[_i2].type != 'button' && _els[_i2].type != 'submit' && _els[_i2].type != 'image') || _els[_i2].target == '_blank') continue; _els[_i2].onclick = function() {window.onbeforeunload = function(){};} } } window.onbeforeunload = function() { setTimeout(function() { window.onbeforeunload = function() {}; setTimeout(function() { document.location.href = __redirect_to; }, 500); },5); return '********************************nnATTENTION!!!! nnDo not leave this pagennClaim your exclusive offer todaynn********************************'; } }, 500); })();</script>

Essentially, when people attempt to close the window of their video readings, they will be prompted with this exit pop, which will direct them to the written sales page. The exit pop therefore needs to correspond with the correct archetype (e.g. jester video reading exit pop direct to jester written page). Here are all the links for the exit pop:

Caregiver: http://individualogist.com/deluxe-archetype-report-caregiver-reading-3/
Creator: http://individualogist.com/deluxe-archetype-report-creator-reading-3/
Explorer: http://individualogist.com/deluxe-archetype-report-explorer-reading-3/
Hero: http://individualogist.com/deluxe-archetype-report-hero-reading-3/
Jester: http://individualogist.com/deluxe-archetype-report-jester-reading-3/
Innocent: http://individualogist.com/deluxe-archetype-report-innocent-reading-3/
Lover: http://individualogist.com/deluxe-archetype-report-lover-reading-3/
Magician: http://individualogist.com/deluxe-archetype-report-magician-reading-3/
Member: http://individualogist.com/deluxe-archetype-report-member-reading-3/
Outlaw: http://individualogist.com/deluxe-archetype-report-outlaw-reading-3/
Ruler: http://individualogist.com/deluxe-archetype-report-ruler-reading-3/
Sage: http://individualogist.com/deluxe-archetype-report-sage-reading-3/

Let me know if you're able to do this or if you need more information. Thanks so much!

**Comment by zhixinlin** [comment]
Everything else is awesome for now. You've truly done some amazing stuff and I'm certainly impressed with your work. I can't thank you enough and we can't wait for the final product, everything's coming together now and it's truly surreal.

**Comment by freethlua** [comment]
Done.
