### ISSUE TITLE
SEPARATE PROJECT: Duplicating Video of Deluxe Sales Portion For Follow Up Sequence

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#23]
Hi Freeth,

Please treat the following as a separate project. We understand you've put a lot of time and effort into the ongoing project, so it wouldn't be fair to throw this at you out of no where. So, please provide us with a quotation for how much this will cost.

As you already know, our sales flow works like this. John takes the quiz, John subscribes to our auto responder, John sees the video reading, John either buys or doesn't buy Deluxe Report. If he doesn't the report on the spot, he will go through a series of autoresponders via e-mail with a link taking him back to the video reading. 

But we don't want people to watch the same thing over and over again. We want to give them the illusion that they're looking at something different. So, part of our autoresponder sequence will consist of call-to-actions to visit the second part of the reading (the deluxe sales portion where it begins with okay, that's all I can share with you for now...).

To do this, here's what we need:

Create New URL: individualogist.com/dar-sales (or something like that)
Design: Follow the same exact template used in attached screenshot (after the styling edits have been made in the previously submitted issue). And please make one addition, display the archetype icon anywhere visible on the text slider, with the name of the archetype underneath, but not too big. I'll leave this up to you.
![screencapture-individualogist-whats-your-archetype-v2-1499142274507](https://user-images.githubusercontent.com/19595715/27815371-4132ad16-60b6-11e7-8fa6-30ed3685f47e.png)
Script: We made a few minor changes to the start of the script, accessible in link below
Voiceover: Please retrieve from here https://drive.google.com/open?id=0B6hspEf5nVh0aWgyazhaRVhVWXM
Exit pop: Same as archetype-v2 slider, exit pop direct to written sales page
Payment links: Same as archetype-v2 slider, detect data saved in browser cache to determine person's archetype. Payment links will follow the same as archetype-v2, changed dynamically to reflect corresponding archetype.

Please let me know if I've missed out anything or if you need more information. So what we'll need is the quote and estimated time to get this done. Nevertheless, awesome work, Freeth!

**Comment by freethlua** [comment]
Partially done. You can link users to `archetype.individualogist.com?deluxe=follow-up`
(test:  http://archetype.individualogist.com?dev&report=free&deluxe=follow-up))


- [ ] Still needs to be done: 

    >And please make one addition, display the archetype icon anywhere visible on the text slider, with the name of the archetype underneath, but not too big.

[Edit: Separated out in #35]

Also this will currently only work if the users visit the link from the same browser they took the quiz from because as you may know the data is stored client-side only. I could make `?archetype=<...>` query option but that would mean anyone who hasn't taken the quiz could also easily land on it. 

Would you have access to aweber data from where you'd send users the link from? If so I might be able to use aweber to pass a token around for authentication. Let me know.

**Comment by zhixinlin** [comment]
Hi Freeth,

Do you mean a custom field in the aweber form needs to be created to pass the authentication token around?

**Comment by wilsonljx** [comment]
Hi Freeth,

There is some slight error for the follow up sliders.

![6](https://user-images.githubusercontent.com/29788050/28007821-89cc3a44-6587-11e7-87fd-208629dbd59a.png)

Also, the pop up should appear as well for them to purchase the respective archetype reports.

**Comment by wilsonljx** [comment]
Also, when I finished listening to the follow up slider, the second part of the sales voice over comes out. "Okay, that's all I can share with you for now..." It shouldn't appear on this slider since we only changed the introduction of the voice over.

**Comment by freethlua** [comment]
I can't identify the error you're referring to in the screenshot above, could you please elaborate. Or was it just popup related?

Could you also please describe the scenario for these cases in full:

* new user takes the quiz and lands on reading page
    
    Currently they hear their specific [archetype].mp3 reading, followed by the "deluxe" mp3.

* user lands on the page via a link with query string `?deluxe=follow-up`

    Currently it just plays that "deluxe-follow-up.mp3". 
   
    I'll make it to show the popup and the links in a moment. 

    Do you want it to play [archetype].mp3 followed by "deluxe-follow-up.mp3"?

**Comment by zhixinlin** [comment]
Hi Freeth,

The issue in the screenshot is a typo in the script, "$200\". Could you help us with removing the slash? This is in the follow-up script. Minor issue, not urgent.

The follow-up video needs to be done in this way:
1. Pop-up area is already displayed upon click, no need for the delay in this query string, and no need for archetype.mp3 to be played either. This should purely be the follow-up script/video.
2. Currently, at the end of the follow-up script/video, the deluxe script/video plays. The deluxe script/video needs to be removed. It should be at the end of the follow-up script/video, everything ends - no continuation. Essentially, just remove the deluxe script/video for query string ?deluxe=follow-up

Here is an overlook of our full funnel, so you'll better understand what's going on:

New user takes quiz > user opts in to archetype list > user is taken to archetype reading > end of archetype reading, deluxe sales mp3 plays > if user doesn't purchase, follow-up emails will be sent to them containing ?deluxe=follow-up (so they won't have to go through the same archetype reading and be taken straight to the sales portion)

**Comment by freethlua** [comment]
>Currently, at the end of the follow-up script/video, the deluxe script/video plays.

Sorry that was a bug, fixed. 

Other things should be fixed too. Please test it out

**Comment by wilsonljx** [comment]
Hi Freeth, thank you for the prompt response. All is well for this issue, please proceed to close it. Thanks!

**Comment by freethlua** [comment]
This still needs to be done: 

>And please make one addition, display the archetype icon anywhere visible on the text slider, with the name of the archetype underneath, but not too big.

It's a tricky one, detailed in #35
