### ISSUE TITLE
Quiz Styling

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#24]
Hi Freeth,

So sorry, missed out some stuff relating to the actual quiz, specifically on the results page where it says Your Archetype Is The [Archetype]...

1. h1 & h2 tags
<h1>Everything You Need To Know About The Caregiver... in One Free Archetype Reading</h1>
<h2>We've prepared a FREE detailed archetype reading telling you about your love, health, and wealth, just for you!</h2>

2. Place 3 free report images into the above pink/yellow container (realize personality of your other half, discover your ideal path, and middle report image). So the arrow down in the pink/yellow container should be slightly overlapping the purple box

3. Last line in the pink/yellow container does not correspond with the correct archetype. e.g. this line is seen in the Caregiver result:

Find out how you can use the "Lover" archetype to overcome anything that life throws at you!

It should be Caregiver instead. I believe this is present in the rest of the results.

That's pretty much it. Thanks, Freeth!

**Comment by freethlua** [comment]
done
