### ISSUE TITLE
Additional Question (Bonus): Animation

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#25]
Hi Freeth

I was wondering if replacing images with CSS animations is difficult. I was thinking of replacing the globe image with this:
https://codepen.io/Coopeh/pen/cnhkF

And adding a bunch of other motions to make the whole thing appear less static and more alive.

Another example:
https://codepen.io/wontem/pen/PqYXop

Or a rotating circular pattern:
i.e. this image http://www.freepik.com/free-vector/mandala-on-blue-watercolor-background_1164062.htm#term=mandala circle&page=1&position=23
And give it an infinite rotation at 20 or 30s until fading out.

I'm not sure how difficult this will be, do let me know your thoughts on this. Thanks :)

**Comment by freethlua** [comment]
Could they be GIF images instead? 

* https://www.google.com/search?q=spinning+globe+gif&tbm=isch
* https://www.google.com/search?q=rotating+circular+pattern+gif&tbm=isch

If so you can just replace the existing static image (like globe) with a GIF image. GIFs are also less CPU intensive than CSS animations (at least than the above ones)

Also currently it can only display 1 image per slide. Would you like to have more than one?

**Comment by zhixinlin** [comment]
Hi Freeth,

I see. 1 image per slide is fine, in which case we'll do it the GIF way then. I'll have this closed. Thanks!

---

(update on this issue copied from #49)

<blockquote>
Recently, numerologist.com has been testing a new variation of their report/reading function.

If you can spare about 5 to 10 minutes, please visit http://video.numerologist.com/free-report-v2/free-report.php (it will give you better insight into what I'm going to talk about next, and do take note of the spinning mandalas).

About a month ago (#25), we had a conversation about gif vs css animations, with your recommendation to use gif. Trouble is, after doing my own research and experiments, I found creating smooth, high quality gifs while maintaining a small file size to be quite the challenge. Making a static image rotate at 360 degrees on repeat at a 60s duration using CSS seems much simpler.

If I'm able to furnish you with the CSS for the animated images, would we be able to test this out on the staging environment to see how it looks? Thanks!
</blockquote>

**Comment by freethlua** [comment]
Sorry about the delay on this. This required a major refactor (#56) which I've just finished with. 

Added just the CSS Globe for now, but the new layout allows adding as many images or even rich components (like the css globe)

Globe component is in [src/components/slider-image-globe](../tree/staging/src/components/slider-image-globe). You can also change the actual map/earth image, the original one was too low-res so I've chosen a different one. 

Haven't added it to (all) the transcripts yet, only the ruler for you to test: http://staging.archetype.individualogist.com/reading?dev&archetype=ruler&seekToIndex=33

**Comment by zhixinlin** [comment]
BEAUTIFUL. Thank you so much for this, it looks wonderful. Please proceed to implement the same element to all archetypes.

While you're at it, please also assist with replacing the spiritual image with the following image:
![mandala](https://user-images.githubusercontent.com/19595715/29259195-3e42e212-80f3-11e7-8043-8243dac327bd.png)

And include the following css styles to make it rotate:
`-webkit-animation:spin 120s linear infinite;
    -moz-animation:spin 120s linear infinite;
    animation:spin 120s linear infinite;
}
@-moz-keyframes spin { 100% { -moz-transform: rotate(360deg); } }
@-webkit-keyframes spin { 100% { -webkit-transform: rotate(360deg); } }
@keyframes spin { 100% { -webkit-transform: rotate(360deg); transform:rotate(360deg); } }`

The appearance of the spiritual image might be a bit brief, so please feel free to lengthen the duration of its appearance - perhaps to last about 10 seconds or slightly longer, to give users something to look at other than text. I'll leave this up to your discretion, as long as the entrance/exit of the image gels nicely with its corresponding text. 

Thanks Freeth!

**Comment by zhixinlin** [comment]
Please also extend the duration for the globe in all archetypes, something as awesome-looking as this must be shown with pride. I'll leave this up to your discretion as well. Thanks, Freeth!

**Comment by freethlua** [comment]
All done. 

Spiritual: http://staging.archetype.individualogist.com/reading?dev&report=free&archetype=caregiver&seekToIndex=109

Globe displays till `confirmToContinue` popup.

**Comment by zhixinlin** [comment]
Excellent! That's about it for the slider/video stylings, we're good with how everything is for now. Thanks so much for your hard work!
