### ISSUE TITLE
Does not work on IE

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#27]

**Comment by zhixinlin** [comment]
Hi Freeth,

Just checking in to find out how big of a problem we're facing. Is this a big problem that needs more time?

**Comment by freethlua** [comment]
This is probably fixed now but some other issues have come up: #28 #29

Please checkout http://individualogist.com/whats-your-archetype-v3/build/ to see if this (IE) and that #26 has been solved.

**Comment by zhixinlin** [comment]
Hi Freeth,

v3/build works for IE, responsive issues have been solved as well. Thank you for the swift response.

I see you've opened the tickets for the styling issues, I'll leave it to you then. Thanks a lot! Let me know if there's anything we can do to make your job easier :)

**Comment by zhixinlin** [comment]
Hi Freeth

Seems that v3/build is down, let me know where you've shifted it to when you get the chance. Thanks!

**Comment by freethlua** [comment]
Works on IE11+
