### ISSUE TITLE
Create a doc: how to edit/configure common things

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#31]
- [x] node/npm basic setup

- [x] tracking codes

- [x] ~~transcript (autogenerate JSONs from TXTs)~~ no longer needed

- [x] slider images

**Comment by freethlua** [comment]
Added some info in [README.md](..#whats-your-archetype) regarding few of the above topics. Let me know if something needs more expansion so far.

**Comment by zhixinlin** [comment]
Hi Freeth,

Thank you for the detailed explanation. Silly question, but how do I run the command node src/utils/parse-transcript/parse-dir? Where does the input go?

**Comment by freethlua** [comment]
Doing `node src/utils/parse-transcript/parse-dir` is no longer necessary.

**Comment by wilsonljx** [comment]
Hi Freeth, 

Let us know when you are done with the documentation and I guess everything will be completed for now! Will send you the payment to Paypal if you prefer to receive payments from there once this is completed:)

We really enjoyed working with you and you have improvised so many features for us! 

Really appreciate that :)

Looking forward to hear from you!

Thanks,
Wilson

**Comment by freethlua** [comment]
Updated README.md, please checkout and let me know if anything needs more elaboration, or if I missed something crucial.

**Comment by freethlua** [comment]
PS: The actual repo that links to the server is not this one on Github but a provate repo on Bitbucket for which I've sent an invite to take ownership to `wilsonljx<at>yahoo.com` (let me know any other email addresses I need to send it to).

**Comment by wilsonljx** [comment]
Hi Freeth,

Please send an invitation to contact@individualogist.com as well.

Thanks,
Wilson

**Comment by wilsonljx** [comment]
Hi Freeth,

I have yet to receive any invitation from Bitbucket. Would you mind sending it once you see this message?

We are trying to make some changes and would appreciate if you could help us as soon as you see this.

Looking forward to hear from you Freeth!

Thanks,
Wilson

**Comment by freethlua** [comment]
Hi there, sent on both emails. You might need to create a bitbucket account with the same email.
