### ISSUE TITLE
preview-page images are all "the hero"

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#32]
The 2 images on either side of archetype report preview-page images all say "the hero" at the top:

![image](https://user-images.githubusercontent.com/8020662/27971816-b1664ff8-6371-11e7-9185-b0b4b3b38b5c.png)

I don't seem to have corresponding images for other archetypes. This issue is also present on the old site.

**Comment by zhixinlin** [comment]
Hi Freeth,

We're aware of this, shouldn't be a problem since the words are blurred out. I'll close this for now. Thanks for highlighting it, though!
