### ISSUE TITLE
Routes and subdomain archetype.individualogist.com

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#33]
Added a new feature that gives routes and paths to various pages:

* `/quiz`
* `/intro`
* `/reading`

This could only be made possible when the app ran from a root path `/` (and not `/whats-your-archetype`)

For this I've added a subdomain: [archetype.individualogist.com](http://archetype.individualogist.com), which is now the new latest URL for this project. 

Issues that needs fixing due to this

- [x] #34 Fix links
- [ ] Re-initialize fb/tracking for each route

**Comment by zhixinlin** [comment]
Hi Freeth,

Tracking should be verified, I'm like 80% sure that everything should be working fine. Thing is, we won't know until we've actually run our Facebook ads to archetype.individualogist.com and the conversions start to show. It's a silly system, but it's pretty much the only foolproof method that FB has for us to verify that the pixels and custom conversions are set correctly.

In which case, we can close this issue for now. Thanks a lot!
