### ISSUE TITLE
Parser improvements: use Mustache.js

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#37]
the parser should use [mustache.js], which handles functions and nested templates pretty well.

[mustache.js]: https://github.com/janl/mustache.js

The only change required would be in the `{{JS:…}}` syntax.

So this:
```js
{{JS:{fn:'displayImage', path:'images/archetype-icons/caregiver.png', fadeIn: true}}}
```
would be changed to this:
```js
{{#displayImage}} {path:'images/archetype-icons/{{archetype}}.png', fadeIn:true} {{/displayImage}}
```

Notice the nested `{{archetype}}.png` - this alone solves #35.

**Comment by zhixinlin** [comment]
Hi Freeth,

I see. Let me know if you'll need our help with changing the syntaxes in the scripts. Thanks!

**Comment by freethlua** [comment]
Done. I've updated the syntax as well.
