### ISSUE TITLE
Authenticate user with a token on ?deluxe=follow-up URL

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#39]
From #23

>This currently only works if the users visit the link from the same browser they took the quiz from because as you may know the data is stored client-side only. 

I could make `?name=<...>&archetype=<...>` query option but that would mean anyone who hasn't taken the quiz could also easily land on it using those query options. This actually already exists, it's just behind a `?dev` query flag which I could easily remove. 

For real authentication it would require server-side code and storing data in a database. 

For now I'm just going with the first option.

**Comment by freethlua** [comment]
Done. Please send the following URL to users for follow-up

```
archetype.individualogist.com/?deluxe&name=[their-name]&archetype=[their-archetype]
```

where `[their-name]` and `[their-archetype]` should be available to you in the Aweber mailer.  Let me know if they're not.

**Comment by zhixinlin** [comment]
Hi Freeth,

It's excellent.

We're able to fetch name tags from aweber by adding {!firstname_fix}. For the archetype, we'll have fill it in with the archetype based on the list that they're subscribed to, i.e. subscribers in the caregiver list will have have links displayed as /?deuxe&name={!firstname_fix}&archetype=Caregiver, where Caregiver is a manual input. This shouldn't be a problem for us, we can have this closed. Thanks, Freeth

**Comment by freethlua** [comment]
PS: use "caregiver" in lowercase

**Comment by wilsonljx** [comment]
Hi Freeth, 

Sorry for the last minute changes and just wondering if you are able to make the archetype logo last for just 5 seconds and after that it will disappear so that they can see the text clearer?

Thanks!

**Comment by freethlua** [comment]
Fixed.
