### ISSUE TITLE
Minor Mobile Optimisation Issue

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#40]
Hi Freeth

Just came across a small issue with the quiz result. Below is the default display immediately after completing the quiz (notice that it's zoomed in)

![img_9309](https://user-images.githubusercontent.com/19595715/28107819-e74db202-671b-11e7-8d3b-f12c6ce12ba4.PNG)

Double tapping adjusts the screen to be how it should actually be:

![img_9310](https://user-images.githubusercontent.com/19595715/28107845-02d2fece-671c-11e7-9c2b-fc6d27efb0c0.PNG)

Could you look into this for me and make it display as seen in the second image? Thanks!

**Comment by freethlua** [comment]
Changed meta tag:

```html
<!--<meta name='viewport' content='width=device-width, initial-scale=1'>-->
<meta name='viewport' content='width=device-width, initial-scale=0.8, maximum-scale=0.8, minimum-scale=0.8, user-scalable=0, target-densityDpi=device-dpi'>
```

Did it work?

**Comment by zhixinlin** [comment]
Perfect. Works like a charm. Will close this then. Thanks again!
