### ISSUE TITLE
Upload New Questions and Point Distribution

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#45]
Hi Freeth,

I'm not too familiar with git and I don't really have the time to figure everything out right now, could you help me out with replacing the questions.js file with the attached file below?

I made some changes to the questions and some of the point distributions, removing duplicates etc. Hoping this will be more accurate. Would be great if you could give it brief look for me to see that the point distribution makes a little bit more sense than the previous one. Thanks a lot!

[questions.txt](https://github.com/freethlua/individualogist-whats-your-archetype/files/1164412/questions.txt)

**Comment by freethlua** [comment]
done.

**Comment by zhixinlin** [comment]
Thanks!
