### ISSUE TITLE
Changes To Popup Area

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#46]
Hi Freeth,

We'd like to make the following changes to the "popup" area in the deluxe sales area (the new popup area should be present throughout all routes). I won't say that this is critical, but we're looking to test the difference in conversions for the implementations below, so it will be greatly appreciated if you could make the changes at your earliest convenience :)

Please note the following additions as seen in the PDF file:

1. Testimonial area below 60 days guarantee, you can refer to this link for the layout or if you're able to add all 6 testimonials. I only displayed 3 in the PDF for illustration purposes.
2. Additional Order Now CTA below Testimonial area
3. FAQ section with accordion (collapsable/expandable content). Please refer to the bottom of this page: individualogist.com/deluxe-archetype-report-caregiver-reading-3/. Content is attached in FAQ Area.docx for easy reference.
4. Final Order Now CTA below FAQ section

[FAQ Area.docx](https://github.com/freethlua/individualogist-whats-your-archetype/files/1169392/FAQ.Area.docx)
[video-template-new.pdf](https://github.com/freethlua/individualogist-whats-your-archetype/files/1169395/video-template-new.pdf)

**Comment by freethlua** [comment]
Done.
