### ISSUE TITLE
Engagement Feature In Reading: Pauses Between Phases Of Video Reading

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#47]
Hi Freeth,

We're looking to improve the overall engagement of the reading. The total duration is pretty long, and we believe that breaking the reading up using pauses will build better engagement, and encourage users to remain on the reading page for the entire duration of the quiz.

Here's a description of the scenario that we want to implement:
1. User watches video/text reading to a certain point...
2. User sees and hears the following line "your riches and fulfilment are merely waiting for you..."
3. Video + audio pauses. An overlay "box" area displays over the reading page with the call-to-action "Would you like to learn more about your path to fulfilment?". Button below with text "Click here to continue". Video resumes upon click.
4. Video reaches another point, and the same overlay "box" area interrupts the video again, but this time with a text field. Users will have to type in "yes" and click on the button to proceed. The purpose of this is to incite more action from the user, and improve the overall engagement of the video.

Essentially, We want this to be added in 1 area in the first part of the reading, and 2 areas in the sales part of the reading.

I believe the best way to do this is to call out a script in the parsed transcription, but I'll leave this up to your decision however you want to achieve this effect.

We will need to test this feature and compare it against the current status quo. That being said, before we proceed with this, please maintain a local backup of the existing reading before making the changes. This will give us the option to revert to the status quo in the event where our experiment fails.

Please let me know if you have any questions and the approximate amount required for this additional feature. Thanks Freeth!

**Comment by freethlua** [comment]
Added main functionality in very basic form, please test it out: http://staging.archetype.individualogist.com/?dev&report=free&archetype=jester&seekToIndex=38 (see #49 for staging site explanation)

A "confirmToContinue" function call [in the transcript](https://github.com/freethlua/individualogist-whats-your-archetype/blob/staging/src/assets/audios/jester.txt#L243) triggers the alert box (for now). 

Note that it should be added to the slide which is meant to be paused for confirmation, i.e. the one after "your riches and fulfilment". 

Let me know the exact design for the dialogue box(es), and the places in transcript (other than the above). 



Backup is maintained in this (and bitbucket) repo, in fact not just a backup but entire history of every change ever made which you can go back to if needed.

**Comment by zhixinlin** [comment]
Hi Freeth,

Thank you for the swift changes. I'm not entirely sure of the limitations for the alert box, but would it be possible to make use of a fullscreen overlay instead? I've attached a psd file for your reference. Let me know if implementing this sort of effect will be possible in place of the alert box.

Thanks!

[fullscreen-overlay-pause.psd.zip](https://github.com/freethlua/individualogist-whats-your-archetype/files/1175846/fullscreen-overlay-pause.psd.zip)

**Comment by freethlua** [comment]
Sorry for the delay. Updated popup, designing it however you like is easy enough. Please test and let me know further changes: http://staging.archetype.individualogist.com/reading?dev&report=free&archetype=caregiver&seekToIndex=40

**Comment by zhixinlin** [comment]
Hi Freeth, no worries and thank you for the update. It looks wonderful. Could you also add the yellow arrows point down to the button as seen in the PSD file? Attached the png file for you below.

![arrow-down](https://user-images.githubusercontent.com/19595715/29013230-39e59d38-7b74-11e7-941e-d190bfc42450.png)

Please proceed to implement the popup to all the other archetypes after adding in the arrow. 

Please also place another popup right before the Deluxe sales reading (or part 2 of the entire reading).

Here's the text for this second popup: 

"[name], we've talked at length about your archetype. Now, I'd like to share with you more about the individuation journey. Click on the button below to continue!"

button "Yes, tell me more about individuation!"

**Comment by freethlua** [comment]
All done. Please test all once more (everything from start possibly, using `?new` in the URL to finish) and give me a final confirmation to move to from staging to master.

**Comment by freethlua** [comment]
<blockquote>
Please assist to remove the pausing features - results aren't showing positive results for this.
</blockquote>

`confirmToContinue`  popups are now disabled from all archetypes and also from the beginning of deluxe reading (both worked with same function which was disabled). 

Changes have been uploaded to master. 

Test here: http://archetype.individualogist.com/reading?dev&report=free&archetype=caregiver&seekToIndex=38 (it would've appeared after the globe faded out but now it doesn't)
