### ISSUE TITLE
Timing Display In Member Reading

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#48]
Hi Freeth,

Please assist with repairing this issue first:

Timestamp is displayed in this portion of the script for the Member archetype. Probably wasn't parsed correctly, but the timings after this slide are not synced correctly since it skipped one slide. Please assist with fixing this, thanks! :)

![screen shot 2017-07-24 at 6 16 41 pm](https://user-images.githubusercontent.com/19595715/28518954-67ab2090-709c-11e7-9b53-2785e08ac00f.png)

**Comment by freethlua** [comment]
This has been fixed.
