### ISSUE TITLE
staging.archetype.individualogist.com

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#49]
New sub-domain [staging.archetype.individualogist.com](http://staging.archetype.individualogist.com) hosts a "staging" version of the site, which is separate from the main production version still hosted on [archetype.individualogist.com](http://archetype.individualogist.com). 

The staging site will contain new features waiting to be approved before merging into the main site. 

In the Git repo it's just the `staging` branch.

**Comment by zhixinlin** [comment]
Hi Freeth,

Thank you for this. The entire purpose of this staging area, as you mentioned, is for experiments and improvements. 

Recently, numerologist.com has been testing a new variation of their report/reading function.

If you can spare about 5 to 10 minutes, please visit http://video.numerologist.com/free-report-v2/free-report.php (it will give you better insight into what I'm going to talk about next, and do take note of the spinning mandalas).

About a month ago (#25), we had a conversation about gif vs css animations, with your recommendation to use gif. Trouble is, after doing my own research and experiments, I found creating smooth, high quality gifs while maintaining a small file size to be quite the challenge. Making a static image rotate at 360 degrees on repeat at a 60s duration using CSS seems much simpler.

If I'm able to furnish you with the CSS for the animated images, would we be able to test this out on the staging environment to see how it looks? Thanks!

**Comment by freethlua** [comment]
Sure. I've re-opened #25 and I'll try to implement that.
