### ISSUE TITLE
5. Caregiver voiceover not in sync

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#5]
5. Caregiver voiceover doesn’t seem to be in sync. Not sure if this is an issue with the transcription, or some other problem. Let me know if the timing in the transcription is off and we’ll correct it for you.

**Comment by freethlua** [comment]
>9. Caregiver and Ruler text sliders and not in sync. There seems to be an additional slide entry in the JS which messes up the timing. Please assist to correct this.

**Comment by freethlua** [comment]
It's an issue with the transcription itself. The start-time for each text in these, is end-time in others. I'll see if I can solve this in the parsing logic.

**Comment by zhixinlin** [comment]
Edit: Moved to https://github.com/freethlua/individualogist-whats-your-archetype/issues/14

**Comment by freethlua** [comment]
Fixed. Test with:

http://individualogist.com/whats-your-archetype-v2/?dev&report=free&archetype=caregiver
http://individualogist.com/whats-your-archetype-v2/?dev&report=free&archetype=creator
http://individualogist.com/whats-your-archetype-v2/?dev&report=free&archetype=ruler

The transcripts have different formats:

**`caregiver.txt`**

```txt
1               // INDEX
Hello {{name}}, // TEXT
00:06           // TIME
```

**`creator.txt`**

```txt
1               // INDEX
00:03           // TIME 
Hello {{name}}, // TEXT
```

Earlier it was parsing the TIME in both formats as "end" time only. 

Now they're parsed correctly. If the TIME occurs before TEXT (2nd format) it parses it as "start" time and otherwise "end" time.

**Comment by zhixinlin** [comment]
Hi Freeth, this is working fine now. Thanks for fixing this!
