### ISSUE TITLE
Feat: Audio fade in/out

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#50]
Playing/pausing the audio (via <kbd>space</kbd> or click) now happens with a slight fade in/out effect by ["tweening"](https://en.wikipedia.org/wiki/Inbetweening) the volume. 

Available to test on [staging.archetype.individualogist.com](http://staging.archetype.individualogist.com).

**Comment by zhixinlin** [comment]
Hi Freeth, excellent feature, please proceed with this. Thanks!

**Comment by freethlua** [comment]
Already added. The delay/fade when pausing is 200ms and when resuming is 1000.
