### ISSUE TITLE
Feat: Play/pause starts with the beginning of current slide

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#51]
Now when you pause in the middle of a sentence and then play again, it'll resume at the start of the sentence. 

```
Don’t worry, everything you need to... [hit pause]
[hit play] Don’t worry, everything you need to know will be on this page.
           ^ starts from beginning of the sentence
```
Available to test on [staging.archetype.individualogist.com](http://staging.archetype.individualogist.com).

**Comment by zhixinlin** [comment]
Hi Freeth, noticed this change without seeing this ticket. Pretty unique, I believe it helps with the user's experience. We'll run with this then, thanks!
