### ISSUE TITLE
{firstname_fix}, Claim Your Discount Now...

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#54]
Just got this email from individuologist as this ^ exact the title. 

Hope this wasn't caused by (or in any other way related) to the recent fix #53

![image](https://user-images.githubusercontent.com/8020662/28983925-5f49e0ae-7979-11e7-8aa9-9895dda6d262.png)

**Comment by zhixinlin** [comment]
Hi Freeth, thank you for notifying us about the issue. Unfortunately it was a typo on our part, so no worries. That tag originates from Aweber, which should be {!firstname_fix} - it's missing the exclamation mark. Please close the issue, but thank you for your initiative and prompt response!
