### ISSUE TITLE
Replace Existing Deluxe Archetype Report Product Images With New Images

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#58]
Hi Freeth,

We've restructured the overall presentation of the Deluxe Archetype Report by breaking it down into sub-reports, forming the entire package. This is intended to make it appear more valuable, detailed, and content-centred, rather than an ordinary single report. We'd like this to be reflected in the updated version of our slider.

Below are 2 images of the revamped deluxe archetype report, please assist us with replacing the existing ones in the deluxe sales portion of the video, as well as within the slider-image. Please use the second image (with the 3 ebooks below) where possible, unless the difference in aspect ratio is difficult to manage, then use the first image (without the 3 ebooks below) instead:

![dar-v2-no-bonus](https://user-images.githubusercontent.com/19595715/29268745-bb666584-8120-11e7-8211-5aca8267f869.png)
![dar-v2-with-bonus-price](https://user-images.githubusercontent.com/19595715/29268746-bb687856-8120-11e7-9f29-03068e99ccda.png)

Let me know if you have any questions, thanks Freeth!

**Comment by freethlua** [comment]
Done. Test here for slider: http://staging.archetype.individualogist.com/deluxe?seekToIndex=250 (ps: audio's out of sync when using `seekTo=…` (#60))

**Comment by zhixinlin** [comment]
Looks perfect, just a minor mobile optimization issue for the images beside the order form on the page, exceeds screen width creating white space - probably specifying max width for the image should fix this, no biggie. Everything else is wonderful. Thanks!

![screen shot 2017-08-16 at 5 46 43 pm](https://user-images.githubusercontent.com/19595715/29357686-e84994e6-82aa-11e7-9725-304d392ce3ed.png)

**Comment by freethlua** [comment]
fixed

**Comment by zhixinlin** [comment]
Hi Freeth,

I believe I commented on another issue to migrate all new changes to the master folder - can't seem to find it now though so I'm not entirely sure if that comment went through.

In any case, please help us with uploading the changes to the master folder whenever you have the time. Thanks again!

**Comment by freethlua** [comment]
Done.

**Comment by wilsonljx** [comment]
Hi Freeth,

Please assist to remove the pausing features - results aren't showing positive results for this. The ones with the "would you like to continue?" interruptions. Let me know if you aren't sure about what I'm talking about. This is an urgent issue - will appreciate your swift action. Thanks Freeth

**Comment by freethlua** [comment]
This one: #47 , right? Am on it.

**Comment by freethlua** [comment]
Done. https://github.com/freethlua/individualogist-whats-your-archetype/issues/47#issuecomment-323651482
