### ISSUE TITLE
6. “pop-up” area isn’t style correctly

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#6]
>6. The “pop-up” area isn’t style correctly, please assist with correcting this and please it hidden until the second part of the text slider/voice over combination is played.

**Comment by freethlua** [comment]
Please expand on this. 

[Here's current layout with labels](https://user-images.githubusercontent.com/8020662/27710467-7b56a014-5d3d-11e7-83c5-70abb04631fd.png)

Should only the `mainContentEl` be visible for the first part (the free reading)?

**Comment by zhixinlin** [comment]
Hi Freeth,

So sorry I must have missed this. The free reading portion should display mainContentEl, footer, and fb comments only. Action 1, action 2, testimonial, and ribbon will only be displayed when the sales portion is played. Action 1 should appear between sections, i.e. half of the container needs to sit on top of the slider. Let me know if you need me to expand on this.

**Comment by freethlua** [comment]
Fixed. Test: http://individualogist.com/whats-your-archetype-v2/?dev&report=free&archetype=jester&seekToIndex=-1
