### ISSUE TITLE
Urgent Issue: Archetype and Sales Reading Play Button Issue On Mobile

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#64]
Hi Freeth,

Just stumbled across a couple of issues on mobile. Autoplay is disabled for mobile devices which requires the display of the play button, but the play button is absent.

1. Start of archetype reading does not display play button - it remains blank until user taps on the screen. 

2. The transition from the archetype text slider reading to the sales reading has the same issue, no display of play button.

Please assist us with displaying the play button on mobile for both areas. This issue is rather urgent as it directly affects sales, so will appreciate your swift action. Do also respond to my e-mail when you have the time. Thanks, Freeth!

Edit: Attached screenshot for your reference

![unnamed](https://user-images.githubusercontent.com/19595715/29655389-85f8bd6e-88e3-11e7-8adb-3670ff18a88d.png)

**Comment by freethlua** [comment]
fixed & uploaded to master
