### ISSUE TITLE
p name=aweber-field tag not parsing space

### ISSUE THREAD

**Issue by zhixinlin** [freethlua/individualogist-whats-your-archetype#65]
Hi Freeth

Just encountered a pretty minor issue with the aweber-field=name tags as seen on:

individualogist.com/deluxe-archetype-report-ruler-reading-3/?name=ooh yu feng&email=linzedex@gmail.com

It isn't parsing spaces in names properly, and displays %20 instead of an actual space. Could you help us with this? Thanks, Freeth!

![screen shot 2017-09-06 at 6 16 56 pm](https://user-images.githubusercontent.com/19595715/30106933-baa6273a-932f-11e7-8630-124e4ac83f74.png)

**Comment by freethlua** [comment]
fixed
