### ISSUE TITLE
8. Quiz results seem imbalanced

### ISSUE THREAD

**Issue by freethlua** [freethlua/individualogist-whats-your-archetype#8]
>8. Quiz results seem imbalanced, Lover Magician and Outlaw are pretty much impossible to get. Please let me know what’s the issue here, it’s probably the computation of the results. Let me know the tweaks that we can make to make sure everything is properly balanced.

**Comment by freethlua** [comment]
I've restored the original answers so it should be exactly how it was in the old (the WP Quiz PRO) version. If it still seems imbalanced please let me know, I'll look at whether there's some error in basic calculation. Otherwise the result you saw were primarily due to me fidgeting with the points of the answers to be "more" balanced, at least in my interpretation, not sure why this affected the results adversely. 

As for the details on what changes I made and why, I had done some analysis (to get the distribution of answers and the count of possible paths of question/answers) which showed the following result:

```
$ node data/test/answer-space
jester    85568 
creator   52784 
outlaw    47104 
hero      45216 
sage      40072 
caregiver 35208 
explorer  31536 
member    26608 
innocent  23728 
magician  21664 
ruler     17784 
lover      8184
```
The result basically means that if you start answering question in all possible combinations (q1a1q2a1..., q1a2q2a2...) then the above distribution shows how many times a particular archetype would occur. Jester had the highest occurrence, lover the lowest (although that's exactly what you get when you check the 1st answer on all questions). 

I don't have the above output for my version of the question/answers currently but it was more evenly distributed. Maybe there's a flaw in analysis itself. I'll look into it later.

**Comment by zhixinlin** [comment]
Hi Freeth,

No worries. This is a pretty minor issue and we can stick to our original distribution for now since it's given us pretty balanced results from our users so far. Thanks!
